sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.27.4

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV=test' app rails action_text:install
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:create
  - docker-compose exec --env 'RAILS_ENV=test' app rails db:migrate
  - docker-compose exec --env 'RAILS_ENV=test' app bundle exec rspec